version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    env_file:
      - .development.env

    ports:
      - ${PORT}:${PORT}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run start:dev api

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - .development.env

    depends_on:
      - api
      - postgres_user

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    
    env_file:
      - .development.env
    
    depends_on:
      - api
      - postgres_user

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run start:dev user

  movie-app:
    build:
      context: .
      dockerfile: ./apps/movie-app/Dockerfile
      target: development

    env_file:
      - .development.env

    depends_on:
      - api
      - postgres_movie

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run start:dev movie-app

  
  postgres_movie:
    image: postgres
    env_file:
      - .development.env
    
    ports:
      - 5431:5432

    volumes:
      - ./initdb.d/movie.initdb.sql:/docker-entrypoint-initdb.d/movie.initdb.sql
      - ./movie_db/data:/var/lib/postgresql/movie/data
      - ./dbbackup/movie-backup.sql:/dbbackup/movie-backup.sql

  postgres_user:
    image: postgres
    env_file:
      - .development.env

    ports:
      - 5433:5432

    volumes:
      - ./initdb.d/user.initdb.sql:/docker-entrypoint-initdb.d/user.initdb.sql
      - ./user_db/data:/var/lib/postgresql/user/data
      - ./dbbackup/user-backup.sql:/dbbackup/user-backup.sql

volumes:
  movie_db:
  user_db:
  initdb: